import type { Metadata } from 'next';
import '@/app/globals.css';
import { SanityLive } from '@/sanity/lib/live';
import { Header } from '@/components/header';
import { DisableDraftMode } from '@/components/disable-draft-mode';
import { draftMode } from 'next/headers';
import { VisualEditing } from 'next-sanity/visual-editing';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function FrontendLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="bg-white min-h-screen">
      <Header />
      {children}
      <SanityLive />
      {(await draftMode()).isEnabled && (
        <>
          <DisableDraftMode />
          <VisualEditing />
        </>
      )}
    </section>
  );
}
